### ISSUE TITLE
Save Agent Replay logs

### ISSUE THREAD

**Issue by marota** [marota/Oracle4Grid#20]
Once we have played the replay of best oracle actions with oracle Agent, we want to save the usual logs of the agent for further analysis, loading them in grid2viz for instance

**Comment by NMegel** [comment]
Done in commit 1492de8d22168313752d5abbf7ec3296f4692a17. Logs are written in a folder replay_logs/ within the output folder.

Using the runner in replay mode introduced some difference in decimals in reward comparison.
This is a separate notion from "reward_significant_digit" of config.ini

In the commit I suggested to introduce a new parameter in the config.ini: replay_reward_rel_tolerance = 1e-7

This parameter provides a configurable threshold in expected cumulated reward relative comparison with the replayed cumulated reward.

All the test currently pass with replay_reward_rel_tolerance = 1e-7

**Comment by NMegel** [comment]
This issue can be closed. Another one has been opened for the relative tolerance threshold
https://github.com/marota/Oracle4Grid/issues/21
