### ISSUE TITLE
Oracle agent does not reconnect attacked lines

### ISSUE THREAD

**Issue by marota** [marota/Oracle4Grid#23]
The Oracle agent replay actions. But we did not take into account the needed reconnections of attacked lines as action. 
We should include that in the agent whenever possible

**Comment by marota** [comment]
Done in dd12b41913b1e13ccbec472807fe5dbcc56b2a0a

Would need a test

**Comment by NMegel** [comment]
Test implemented in commit ca3ef7c53e347453bb9ecbfa279262ee3b553405

**Comment by NMegel** [comment]
We shoud have in mind that the reconnection may add an action on a different line to the current oracle action. If the game rule is strict (MAX_LINE_CHANGED is low), it might be impossible to combine these actions in one time step and then return a violation
