### ISSUE TITLE
Bad no_overload_path return when there is no end to end path between init and end nodes

### ISSUE THREAD

**Issue by marota** [marota/Oracle4Grid#25]
if at some timestep, every configuration is overloaded, there will be no path from 'init' to 'end' without any overload.
In that case the currently returned best_no_overload_path is wrong, and sometime don't even deal integrate 'init' or 'end' node

**Comment by marota** [comment]
Done in 0e47eaccb574ae5e3b171fbfaeed97ddc256626b
We should have a test for that case

**Comment by marota** [comment]
Cas Test: ne jouer qu'un action, comme le do-nothing et observer une surcharge à un moment

**Comment by NMegel** [comment]
Test implemented in commit abd087716f4c3709a3df8eb1fedc665d190c86e7

Added also some correction when overloads are on every timesteps
