### ISSUE TITLE
Action parsing not working if only line actions in dictionnary

### ISSUE THREAD

**Issue by marota** [marota/Oracle4Grid#26]
If you only give as an input action dictionary {
  "line": {"13": [{"set_line": -1}],"9":[{"set_line": -1}] }
} an error is returned "incompatible json dictionary.

But it works as soon as you add in the dictionary an action with sub such as:
{
  "sub": {		"28":
			[{"lines_id_bus": [[42, 2], [44, 2], [57, 2]]}]
  },
  "line": {"13": [{"set_line": -1}],"9":[{"set_line": -1}] }
}

**Comment by NMegel** [comment]
Done in commit df0933ae8e932d5086698afd410459692f9a6e84
